const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');const {zipSync,strToU8}=require('fflate');
const {parseDocument,unpack,xml,excelDate}=require('../src/documents.cjs');const {analyze}=require('../src/analyzer.cjs');const {reportCsv,reportHtml}=require('../src/report.cjs');
const zip=obj=>Buffer.from(zipSync(Object.fromEntries(Object.entries(obj).map(([k,v])=>[k,strToU8(v)]))));
const para=s=>`<hp:p><hp:run><hp:t>${s}</hp:t></hp:run></hp:p>`;
const hwpx=(s,extra={})=>zip({'Contents/section0.xml':`<hs:sec xmlns:hs="s" xmlns:hp="p">${s}</hs:sec>`,...extra});
const doc=(lines,id='one')=>parseDocument(hwpx(lines.map(para).join('')),id+'.hwpx');
const samples=()=>fs.readdirSync(path.join(__dirname,'../assets/samples')).map(n=>parseDocument(fs.readFileSync(path.join(__dirname,'../assets/samples',n)),n));
function xlsx(sheet,extra={}){return zip({'xl/workbook.xml':'<workbook xmlns="x" xmlns:r="r"><sheets><sheet name="예산" r:id="r1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<Relationships><Relationship Id="r1" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':`<worksheet xmlns="x"><sheetData>${sheet}</sheetData></worksheet>`,...extra});}
test('real sample bundle reads 3 files and detects all six seeded issues',()=>{const ds=samples(),r=analyze(ds,{year:2026});assert.equal(ds.length,3);assert.equal(r.issues.length,6);for(const kind of ['date','year','people','money','calculation'])assert.ok(r.issues.some(i=>i.kind===kind),kind);assert.ok(r.issues.every(i=>i.evidence.every(e=>e.location&&e.excerpt)));});
test('matching documents produce no false mismatch',()=>{const a=doc(['참가 인원: 118명','총예산: 2,950,000원','행사일: 2026. 10. 23. (금)'],'a'),b=doc(['참가 인원: 118명','총예산: 2950000원','행사일: 2026-10-23'],'b');assert.equal(analyze([a,b],{year:2026}).issues.length,0);});
test('student, teacher and total are not conflated',()=>{const r=analyze([doc(['학생 수: 118명','인솔 인원: 6명'],'a'),doc(['학생 수: 118명','총 인원: 124명'],'b')],{year:2026});assert.equal(r.issues.length,0);});
test('event date and deadline are separate',()=>{const r=analyze([doc(['행사일: 2026-10-23'],'a'),doc(['제출 마감일: 2026-10-16'],'b')],{year:2026});assert.equal(r.issues.length,0);});
test('invalid dates are flagged, leap years supported',()=>{assert.equal(analyze([doc(['행사일: 2026-02-30'])],{year:2026}).issues[0].severity,'error');assert.equal(analyze([doc(['행사일: 2028-02-29'])],{year:2028}).issues.length,0);});
test('date without year uses chosen reference year',()=>{const r=analyze([doc(['행사일: 10월 23일 (금)'])],{year:2026});assert.equal(r.facts[0].value,'2026-10-23');assert.equal(r.issues.length,0);});
test('multiple dates in one field are not guessed',()=>{assert.equal(analyze([doc(['일정: 2026-10-23 ~ 2026-10-25'])],{year:2026}).facts.length,0);});
test('historical dates do not trigger stale-date warning',()=>{const r=analyze([doc(['행사일: 2025-10-23 (작년 실적)'])],{year:2026});assert.equal(r.issues.length,0);});
test('ambiguous repeated values are flagged for comparison scope',()=>{const r=analyze([doc(['참가 인원: 118명','참가 인원: 120명'],'a'),doc(['참가 인원: 118명'],'b')],{year:2026});assert.match(r.issues[0].title,/비교 기준/);});
test('HWPX mixed runs and multiple sections read once',()=>{const b=hwpx('<hp:p><hp:run><hp:t>참가 </hp:t></hp:run><hp:run><hp:t>인원: 118명</hp:t></hp:run></hp:p>',{'Contents/section1.xml':'<hs:sec xmlns:hs="s" xmlns:hp="p">'+para('장소: 공원')+'</hs:sec>'});const d=parseDocument(b,'t.hwpx');assert.equal(d.blocks.length,2);assert.equal(d.blocks[0].text,'참가 인원: 118명');assert.match(d.blocks[1].location,/구역 2/);});
test('HWPX table cell addresses use actual merged-cell coordinates',()=>{const b=hwpx('<hp:p><hp:run><hp:tbl><hp:tr><hp:tc><hp:cellAddr rowAddr="2" colAddr="3"/><hp:subList>'+para('참가 인원')+'</hp:subList></hp:tc><hp:tc><hp:cellAddr rowAddr="2" colAddr="5"/><hp:subList>'+para('118명')+'</hp:subList></hp:tc></hp:tr></hp:tbl></hp:run></hp:p>');const d=parseDocument(b,'table.hwpx');assert.equal(d.blocks.length,1);assert.match(d.blocks[0].cells[1].location,/3행 6열/);assert.equal(analyze([d]).facts[0].value,'118');});
test('nested tables do not duplicate inner paragraphs into outer cells',()=>{const b=hwpx('<hp:p><hp:run><hp:tbl><hp:tr><hp:tc><hp:subList>'+para('외부')+'<hp:p><hp:run><hp:tbl><hp:tr><hp:tc><hp:subList>'+para('내부')+'</hp:subList></hp:tc></hp:tr></hp:tbl></hp:run></hp:p></hp:subList></hp:tc></hp:tr></hp:tbl></hp:run></hp:p>');const d=parseDocument(b,'nested.hwpx');assert.equal(d.blocks.length,2);assert.equal(d.blocks.filter(b=>b.text.includes('내부')).length,1);});
test('XLSX shared strings and sparse cell addresses are preserved',()=>{const b=xlsx('<row r="7"><c r="A7" t="s"><v>0</v></c><c r="D7"><v>118</v></c></row>',{'xl/sharedStrings.xml':'<sst xmlns="x"><si><t>참가 인원</t></si></sst>'});const d=parseDocument(b,'test.xlsx'),r=analyze([d]);assert.equal(r.facts[0].value,'118');assert.equal(r.facts[0].location,'예산!D7');});
test('XLSX inline string rich text joins all runs',()=>{const b=xlsx('<row r="1"><c r="A1" t="inlineStr"><is><r><t>참가 </t></r><r><t>인원</t></r></is></c><c r="B1"><v>118</v></c></row>');assert.equal(analyze([parseDocument(b,'rich.xlsx')]).facts[0].value,'118');});
test('XLSX formulas without cache are warned, not zero-filled',()=>{const b=xlsx('<row r="1"><c r="A1" t="inlineStr"><is><t>총액</t></is></c><c r="B1"><f>SUM(C1:D1)</f></c></row>');const d=parseDocument(b,'formula.xlsx');assert.ok(d.warnings.some(w=>w.includes('수식 결과가 없습니다')));assert.equal(analyze([d]).facts.length,0);});
test('XLSX cached formula and date style are read',()=>{const b=xlsx('<row r="1"><c r="A1" t="inlineStr"><is><t>행사일</t></is></c><c r="B1" s="1"><v>46318</v></c></row><row r="2"><c r="A2" t="inlineStr"><is><t>총액</t></is></c><c r="B2"><f>100*2</f><v>200</v></c></row>',{'xl/styles.xml':'<styleSheet xmlns="x"><cellXfs><xf numFmtId="0"/><xf numFmtId="14"/></cellXfs></styleSheet>'});const d=parseDocument(b,'date.xlsx');assert.ok(d.blocks[0].cells[1].text.startsWith('2026-'));assert.equal(analyze([d],{year:2026}).facts.find(f=>f.kind==='money').value,'200');});
test('Excel 1904 epoch supported',()=>{assert.equal(excelDate(0,true),'1904-01-01');assert.equal(excelDate(61,false),'1900-03-01');});
test('unsupported extension is rejected',()=>assert.throws(()=>parseDocument(Buffer.from('x'),'a.hwp'),/HWPX/));
test('corrupt and empty archives show useful errors',()=>{assert.throws(()=>parseDocument(Buffer.from('bad'),'a.xlsx'),/손상|암호화/);assert.throws(()=>parseDocument(zip({'a.xml':'<a/>'}),'a.hwpx'),/본문/);});
test('external entity XML is rejected',()=>assert.throws(()=>xml(strToU8('<!DOCTYPE a [<!ENTITY e SYSTEM "file:///secret">]><a>&e;</a>')),/엔티티/));
test('malformed XML is rejected',()=>assert.throws(()=>xml(strToU8('<a><b></a>')),/XML|tag|element|parse/i));
test('oversized decompressed XML is rejected before decompression',()=>assert.throws(()=>unpack(zip({'big.xml':'x'.repeat(17*1024*1024)})),/크기/));
test('unrecognized text is not claimed as validated',()=>{const r=analyze([doc(['안녕하세요','이 자료에는 비교 가능한 라벨이 없습니다.'])]);assert.equal(r.facts.length,0);assert.equal(r.coverage[0].count,0);});
test('HTML report escapes document contents and CSV neutralizes formulas',()=>{const r=analyze([doc(['참가 인원: 118명'],'a'),doc(['참가 인원: 120명'],'b')]);r.issues[0].evidence[0].excerpt='<script>alert(1)</script>';r.issues[0].evidence[0].fileName='=CMD()';assert.ok(!reportHtml(r).includes('<script>'));assert.ok(reportHtml(r).includes('&lt;script&gt;'));assert.ok(reportCsv(r).includes("'=CMD()"));assert.ok(reportCsv(r).startsWith('\uFEFF'));});
test('analysis never mutates original bytes or documents',()=>{const ds=samples(),before=JSON.stringify(ds);analyze(ds,{year:2026});assert.equal(JSON.stringify(ds),before);});
test('invalid reference year rejected',()=>assert.throws(()=>analyze([],{year:1800}),/연도/));
test('negative or fractional people are flagged rather than truncated',()=>{for(const v of ['-2명','118.5명']){const r=analyze([doc(['참가 인원: '+v])]);assert.equal(r.facts.length,0);assert.equal(r.issues[0].severity,'error');}});
test('unsupported Korean currency scales are not partially parsed',()=>{const r=analyze([doc(['총예산: 2만5,000원'])]);assert.equal(r.facts.length,0);});
test('zero is a valid explicit count, missing values remain missing',()=>{const r=analyze([doc(['참가 인원: 0명','총예산: 미정'])]);assert.equal(r.facts.length,1);assert.equal(r.facts[0].value,'0');});

test('explicit years outside the 2000s are read in full without partial matches',()=>{
  for(const year of [1999,2100]){const r=analyze([doc([`행사일: ${year}-10-23`])],{year:2100});assert.equal(r.facts[0]?.value,`${year}-10-23`);}
  for(const value of ['2026-10-230','20260-10-23'])assert.equal(analyze([doc(['행사일: '+value])],{year:2026}).facts.length,0);
});
